### PR TITLE
Unclear how to access the API from reading this

### PR DESCRIPTION
**Pull request by matthiasdebernardini**
It was not clear to me how to access the API in the terminal from reading this document, therefore would like to add a minimal example of how to use esplora and curl together.

### CODE REVIEW

**Comment by matthiasdebernardini** [comment]
If this is too long, I think some mention of which route to take to access the API should be added

**Comment by greenaddress** [comment]
Try to open this in a browser https://blockstream.info/api/blocks/tip/hash (or curl or wget or python urlib or python requests, etc)

**Comment by greenaddress** [comment]
utack 9c633ec61e10230997538ccdca6f44bfb0a48663

**Comment by shesek** [comment]
I added some more information about the public APIs in https://github.com/Blockstream/esplora/commit/0af3acab6267df8d1d3f74741044c05ad7ee3311.

**Pull request closed without merging**
