### PR TITLE
WebSocket frontend for the Electrum JSONRPC server

### PR DESCRIPTION
**Pull request by shesek**
Using [websocat](https://github.com/vi/websocat) as a WebSocket to TCP bridge, with an nginx frontend.

    nginx --[unix socket]-> websocat --[tcp loopback]-> electrs

### CODE REVIEW

**Comment by greenaddress** [comment]
utack 69071260c300d33b35339409f12841966c55d25d

**Comment by andreabonel** [comment]
Given that the problem we found is related to the deployment (timeout) and not to the code, should we merge this?

**Comment by greenaddress** [comment]
utack 6ada4e4782a92ce6ebaccc2d5cc3c6570768063a

**Comment by greenaddress** [comment]
merged in c8132078cd76ca23dd67923d02398fbb0498c33e

**Comment by tiero** [comment]
Not clear, is Electrs/Esplora supporting websocket for the electrum JSONRPC?  Do you have any example to point me on how to use it?

**Comment by andreabonel** [comment]
I have a basic example, I'll send it to you over telegram.

**Comment by birozuru** [comment]
Hello @andreabonel 
Can I also get an example on how to use the websocket on esplora for the electrum JSONRPC as `wss://$DOMAIN_NAME/signet/api/v1/ws` does not work

**Comment by andreabonel** [comment]
Hello @birozuru 
Sorry for the delayed response, I hadn't seen your message.
This is a simple example: https://gist.github.com/andreabonel/acfbd4060841325cb2c62e0813682b93
Please let me know if I can help you with anything ;)

**Comment by shesek** [comment]
The Electrum WebSocket server is available at `/electrum-websocket`, for example https://blockstream.info/electrum-websocket for mainnet or https://blockstream.info/testnet/electrum-websocket for testnet.

**Comment by velaandre** [comment]
### +524681000609

**Pull request closed without merging**
